_posts/2016-09-03-como-se-manter-atualizado-no-frontend.md

Added link https://umaar.com/dev-tips/, a weekly about features and how to use Chrome Devtools

Added Link in Weekly

---

_posts/2016-09-03-como-se-manter-atualizado-no-frontend.md

Just added some links to reddit :)

Add reddit as resource in how to be up to date post

---

_posts/2016-09-03-como-se-manter-atualizado-no-frontend.md

Adicionando seção com canais do Youtube

Update 2016-09-03-como-se-manter-atualizado-no-frontend-Adicionando seção com canais do Youtube

---

_posts/2016-09-03-como-se-manter-atualizado-no-frontend.md

English: DevTips, Codecourse.
Portuguese: BrazilJS, CSS Cast Show, Gravento, Elcio Ferreira, Estevan Maito.

added youtube channels

---

_posts/2016-09-03-como-se-manter-atualizado-no-frontend.md

Added css-tricks - Chrys Coyier Youtube Channel.

---

_posts/2016-09-03-como-se-manter-atualizado-no-frontend.md

Add some new links

---

_posts/2015-02-24-como-se-tornar-um-desenvolvedor-front-end.md

Hey, Justen! 
I fixed the CodeSchool name!
I love your job! See ya!

Fixing CodeSchool

---

_posts/2017-01-08-vindo-morar-e-estudar-na-irlanda.md

Apenas uma pequena correção no início do post, acredito que tenha faltado a palavra "mundo". :smile:

Pequena correção no início do post

---

_posts/2018-02-08-guia-como-contribuir-em-open-source.md
package-lock.json

Following your tips and making my first contributing to some portuguese errors and typing.

Correction of portuguese errors and typing

---

_posts/2018-02-08-guia-como-contribuir-em-open-source.md

Inspirado pelo post achei uma leve correção para fazer no texto :)

Update "num post" para "num posto" na linha 261

---

_posts/2018-02-08-guia-como-contribuir-em-open-source.md

Adicionei um link pro [BackendBr](http://github.com/backend-br/forum) no último post sobre Open Source

add link to backend br

---

_posts/2015-07-14-como-usar-o-reactjs.md
_posts/2015-07-17-o-basico-da-api-do-reactjs.md
_posts/2016-06-03-utilizando-svg-sprites-com-react.md
_posts/2016-06-19-configurando-o-webpack-para-rodar-react-e-es6.md
_posts/2016-07-30-refatorando-componentes-react-para-es6.md

Códigos atualizados para as breaking changes da versão 15.4 ou inferior para as versões após a 15.5

Série sobre React atualizada

---

_posts/2019-02-08-habemus-react-hooks.md

Fix typo 2019-02-08-habemus-react-hooks

---

src/components/Seo.js

Remove unused defaultImage in defaultProps object

Remove unused var

---

posts/2018-03-20-perfomance-web-critical-css-e-jekyll.md

Desculpe, passei por despercebido, tinha outro link quebrado

Update link (file default.html)

---

posts/2018-06-04-como-criar-um-spinner-loader-com-css-puro-e-uma-div.md

Relacionar o keyframe com o nome 'spin' no exemplo do post.

Ajuste keyframe

---

posts/2020-05-18-mini-curso-gratuito-de-typescript.md

Modifiquei um pouco para que a palavra "encontrem" se adeque na frase. Veja o que acha.

Ajuste de palavras

---

posts/2020-06-30-a-historia-por-tras-do-meu-curso-de-react-avancado.md

Por alguma razão o redirect do bitly não está funcionando com / no final, ajustei apenas isso.

Ajuste link slack

---

posts/2021-02-21-juntando-arrays-e-objetos-com-spread-syntax-no-javascript.md

The filename and the post's title for 2021-02-21 were corrected.

Post's title corrected

---

src/styles/base.js
src/templates/blog-post.js

Added back button on post

---

posts/mude.md

Hey, Will.
Eu estava lendo seus posts e me deparei com essa _quote_.
Não sei se foi proposital, mas, se não foi, ai está um PRzinho pra ajudar! :D

fix (?) blockquote
